#!/bin/bash
echo Creating blank coin_monitor.root
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_init.C"

# Hydrogen
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2278,1)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2279,1)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2280,1)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2281,1)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2283,1)"

# Carbon
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2284,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2285,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2286,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2290,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2291,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2292,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2293,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2294,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2295,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2296,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2297,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2298,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2299,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2300,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2301,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2303,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2304,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2305,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2306,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2308,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2309,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2310,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2311,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2312,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2313,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2314,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2315,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2316,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2317,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2318,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2319,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2320,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2321,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2322,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2323,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2324,2)"
./hcana -q "SCRIPTS/COIN/MONITOR/coin_monitor_calc.C(2325,2)"
